"""add_workflow_json

Revision ID: 257b3af87f7f
Revises: ccef3512b363
Create Date: 2026-06-23 23:25:52.482365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257b3af87f7f'
down_revision: Union[str, Sequence[str], None] = 'ccef3512b363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('workflow_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'workflow_json')
    # ### end Alembic commands ###
